---
- name: add apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: add apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    filename: docker

- name: install packages
  apt:
    name:
     - docker-ce
    update_cache: yes

- name: install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: "0755"
